//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porthole.Pages.Layouts {
	
	
	public partial class ControlTemplate {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cphTitle;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder cphForm;
	}
}
