//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porthole.Pages.Controls.Student {
	
	
	public partial class UpdateProfile {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.TextBox txtAchievement;
		
		protected System.Web.UI.WebControls.CheckBoxList cblSkills;
		
		protected System.Web.UI.WebControls.TextBox txtURL;
		
		protected System.Web.UI.WebControls.Label lblInfo;
		
		protected System.Web.UI.WebControls.Button btnReset;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
