//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porthole.Pages.Controls.Student {
	
	
	public partial class UpdateProject {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Literal lTitle;
		
		protected System.Web.UI.WebControls.TextBox txtTitle;
		
		protected System.Web.UI.WebControls.TextBox txtDescription;
		
		protected System.Web.UI.WebControls.TextBox txtReflections;
		
		protected System.Web.UI.WebControls.CheckBoxList cblCollaborators;
		
		protected System.Web.UI.WebControls.Label lblInfo;
		
		protected System.Web.UI.WebControls.Button btnReset;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
