//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porthole.Pages.Controls.Mentor {
	
	
	public partial class ChangePassword {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPassword;
		
		protected System.Web.UI.WebControls.TextBox txtNewPassword2;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator2;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.Label lblInfo;
	}
}
