//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porthole.Pages.Controls.Mentor {
	
	
	public partial class UpdateSuggestions {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox txtInput;
		
		protected System.Web.UI.WebControls.Button btnSend;
	}
}
